sudo: false
language: node_js
node_js:
    - "12"
    - "node"

cache: npm

install:
    - npm install -g codecov snyk
    - npm ci

script:
    - npm test
    - codecov
    - snyk test

after_success:
    - snyk monitor
